### ISSUE TITLE
Offer to maintain the gem

### ISSUE THREAD

**Issue by ndbroadbent** [ndbroadbent/libreconv#19]
Hello,

I'm working on a service called [FormAPI](https://formapi.io/), and we also have a GitHub account: https://github.com/FormAPI

If you are still looking for a maintainer, I'd be happy to keep it updated for newer versions of Ruby / Rails / LibreOffice.

**Comment by ricn** [comment]
Hi,

That would be awesome! Do you want me to transfer the repository to your username or the formapi organization?

**Comment by ndbroadbent** [comment]
Hi, the formapi organization would be great!

**Comment by ricn** [comment]
I had to transfer it to your username instead because I needed creation permissions in the formapi organization to transfer it to the organization.

**Comment by ndbroadbent** [comment]
Ah no problem, I'll transfer to the organization. Thanks!

**Comment by ndbroadbent** [comment]
Hi @ricn, I was wondering if you could also please give me access to the libreconv gem on RubyGems? https://rubygems.org/gems/libreconv

I would like to release some new versions. Thanks!

**Comment by ricn** [comment]
Hi,

I will take a look at it later tonight.

**Comment by ndbroadbent** [comment]
Hi @ricn, sorry I was just wondering if you would still be able to give me access to the libreconv gem on RubyGems? I'm going to merge a PR now and would like to release a new version of the gem. Thanks!

**Comment by ricn** [comment]
I can't find a way to transfer the gem... Do you know how to do that?

**Comment by ndbroadbent** [comment]
Hello, I [found this forum post](https://help.rubygems.org/discussions/questions/151-adding-another-owner), so it looks like you can run this command:

```
$ gem owner --add nathan.f77@gmail.com libreconv
```

**Comment by ricn** [comment]
Ah thanks I will try it as soon as I'm home from work.

**Comment by ricn** [comment]
You have now been added as an owner.
